import { ArrowLeft, ExternalLink, GitBranch, LockKeyhole, Globe2 } from "lucide-react";
import { Link, useParams } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { repositoryCatalog } from "@/data/repositoryCatalog";
import { slugFor } from "./RepositoryLibrary";

export default function RepositoryDetail() {
  const { slug } = useParams<{ slug: string }>();
  const repo = repositoryCatalog.find((record) => slugFor(record.name) === slug);
  if (!repo) return <div className="min-h-screen bg-background px-4 py-12"><div className="mx-auto max-w-2xl"><Card className="border-white/10 bg-card/70 p-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">Repository record</p><h1 className="mt-3 text-3xl font-bold text-foreground">Record not found</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">This catalog only opens records from the current source snapshot. No matching entry was found.</p><Link href="/projects" className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-accent"><ArrowLeft className="h-4 w-4" /> Back to library</Link></Card></div></div>;
  const visibilityIcon = repo.visibility === "public" ? <Globe2 className="h-4 w-4" /> : <LockKeyhole className="h-4 w-4" />;
  return <div className="min-h-screen bg-background"><main className="mx-auto max-w-4xl space-y-6 px-4 py-7 sm:px-6 lg:px-8"><Link href={repo.category === "Projects" ? "/projects" : repo.category === "Frameworks" ? "/frameworks" : "/prompt-skills"} className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Back to {repo.category}</Link><Card className="border-accent/20 bg-gradient-to-br from-accent/[0.1] via-card/90 to-violet-500/[0.08] p-6 sm:p-9"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="border-accent/30 text-accent">{repo.category}</Badge><Badge variant="outline" className={repo.visibility === "public" ? "border-emerald-400/30 text-emerald-300" : "border-violet-400/30 text-violet-300"}>{visibilityIcon}<span className="ml-1">{repo.visibility}</span></Badge></div><p className="mt-6 text-sm font-medium text-muted-foreground">{repo.owner}</p><h1 className="mt-2 break-words text-4xl font-bold tracking-[-0.04em] text-foreground sm:text-6xl">{repo.name}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground">{repo.description || "No repository description was provided by the source."}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href={repo.url} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-accent px-5 text-sm font-semibold text-accent-foreground hover:bg-accent/90">Open on GitHub <ExternalLink className="h-4 w-4" /></a><span className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm text-muted-foreground"><GitBranch className="h-4 w-4" /> Source-linked catalog record</span></div></Card><section className="grid gap-4 sm:grid-cols-3"><Card className="border-white/10 bg-card/60 p-5"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Owner</p><p className="mt-2 font-semibold text-foreground">{repo.owner}</p></Card><Card className="border-white/10 bg-card/60 p-5"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Visibility</p><p className="mt-2 font-semibold capitalize text-foreground">{repo.visibility}</p></Card><Card className="border-white/10 bg-card/60 p-5"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Snapshot date</p><p className="mt-2 font-semibold text-foreground">{new Date(repo.updatedAt).toLocaleDateString()}</p></Card></section><Card className="border-white/10 bg-card/50 p-5"><p className="text-sm leading-6 text-muted-foreground">This page presents metadata from the repository snapshot. It does not infer stars, forks, quality scores, or project status when those values were not collected.</p></Card></main></div>;
}
